name: symfony

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: ["symfony/Dockerfile"]

jobs:
  push_to_registry:
    name: Push symfony Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jefvda/symfony
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./symfony/Dockerfile
          push: true
          tags: jefvda/symfony:latest
          labels: ${{ steps.meta.outputs.labels }}
